name: Zach Bajaber
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
collections:
  projects:
    output: true
    permalink: /work/:path/
